apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dnai
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-dnai@sha256:1238fa7d0ae3d3cab8cb81ac388e2d21fefd680a68c1fc180e7751cdeba669cb
        name: my-nodejs
        resources: {}
status: {}
